### ISSUE TITLE
Adding a layer to inactive (but added scene) error.

### ISSUE THREAD

**Issue by ohmslaw** [XervoIO/pulse#10]
When I was flipping between the game scene and menu scene I dumped and add a couple layers based content.  I noticed that if I added the layer before activating the scene the draw loop errors because the orderedKeys don't match up with the liveLayers.  It is not really a big deal because I can always activate the scene before any layer manipulation but thought it might be a bug.

It did cross my mind that layers should probably be more fixed then I treat them but this is pretty rough first attempt.

**Comment by tzmanics** [comment]
Hi @ohmslaw sorry for the big delay in response, we aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for `Pulse` we'll look into how manage the `orderedKeys` and `liveLayers` mismatch.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
