### ISSUE TITLE
Bug on remove layer

### ISSUE THREAD

**Issue by LeonardoFerrer** [XervoIO/pulse#11]
When you add a layer, it's info is saved on the layers, orderedkeys and liveLayers arrays and when you remove it it's only deleted from layers and liveLayers.

I think adding this line to the line 3319 of the full pulse file fixes it: 

this._private.orderedKeys = pulse.util.getOrderedKeys(this.layers);

**Comment by tzmanics** [comment]
Hi @LeonardoFerrer sorry for the big delay in response, we aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for `pulse` we'll post an update on the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
