### ISSUE TITLE
Not all layers make sprites visible (Max layer cap?)

### ISSUE THREAD

**Issue by JBRPG** [XervoIO/pulse#12]
Update: I tweaked around and it looks like it supports up to 6 layers in alphabetical order from my experience. Any more than that, it will cause graphical issues

I have attempted to make several sprites that use multiple layers, but I cannot get all of them to show up.. Is there a cap on the number of layers Pulse can support?

If not, please fix it ASAP

The 1st image shows initialized layers

2nd image shows a sprite that is supposed to show up

3rd image shows the game, but the sprite image does not show up..

I have chosen image from correct directory, and did everything else, but the one sprite does not show up

![Screen shot 2013-03-08 at 3 42 48 PM](https://f.cloud.github.com/assets/3642100/238849/17c3a35c-884a-11e2-9028-f483a6f302c6.png)
![Screen shot 2013-03-08 at 3 43 02 PM](https://f.cloud.github.com/assets/3642100/238850/17c2b960-884a-11e2-9342-0e25071e4b3a.png)
![Screen shot 2013-03-08 at 3 43 54 PM](https://f.cloud.github.com/assets/3642100/238848/17ca63b8-884a-11e2-94fb-df3418ec2450.png)

**Comment by tzmanics** [comment]
Hi @JBRPG sorry for the big delay in response, we aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for `pulse` we'll post an update on the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
